/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 27.12.2009, 15:01:48
 */

package fehlercodesclasses;

/**
 *
 * @author Christian
 */
public class GUI extends javax.swing.JFrame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        calcButton = new javax.swing.JToggleButton();
        codewoerter = new javax.swing.JRadioButton();
        syndrome = new javax.swing.JRadioButton();
        korregieren = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        generatormatrix = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ausgabe = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calcButton.setText("Calc");
        calcButton.setName("null"); // NOI18N
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(codewoerter);
        codewoerter.setSelected(true);
        codewoerter.setText("Codewörter");

        buttonGroup1.add(syndrome);
        syndrome.setText("Syndrome");

        buttonGroup1.add(korregieren);
        korregieren.setText("Korregieren");

        jLabel1.setText("Generatormatrix");

        generatormatrix.setColumns(20);
        generatormatrix.setRows(5);
        generatormatrix.setText("1000011\n0100101\n0010110\n0001111");
        generatormatrix.setName("null"); // NOI18N
        jScrollPane1.setViewportView(generatormatrix);

        ausgabe.setColumns(20);
        ausgabe.setRows(5);
        jScrollPane2.setViewportView(ausgabe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codewoerter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(syndrome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(korregieren)
                        .addGap(67, 67, 67)
                        .addComponent(calcButton)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(87, 87, 87)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(158, 158, 158))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addContainerGap(498, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codewoerter)
                    .addComponent(syndrome)
                    .addComponent(korregieren)
                    .addComponent(calcButton))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        String ausgabe = "NULL";
        Manager manager = new Manager();
        BitMatrix2D matrix = new BitMatrix2D(this.generatormatrix.getText());

        if (this.codewoerter.isSelected())
          ausgabe = manager.codewoerter(matrix);

        if (this.syndrome.isSelected())
            ausgabe = manager.syndrome(matrix);

        if (this.korregieren.isSelected());

        this.ausgabe.setText(ausgabe);
    }//GEN-LAST:event_calcButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ausgabe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton calcButton;
    private javax.swing.JRadioButton codewoerter;
    private javax.swing.JTextArea generatormatrix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton korregieren;
    private javax.swing.JRadioButton syndrome;
    // End of variables declaration//GEN-END:variables

}
